/* ============ FORMS ============ */
const YN=["Full-time","Contract","Internship"],EXP=["0–2 years","3–5 years","6–10 years","10+ years"];
const FM={
employer:{btn:"Submit Hiring Requirement",ok:"Requirement received. Our recruitment team will contact you shortly.",f:[["name","Name","text",1],["company","Company name","text",1],["email","Business email","email",1],["phone","Phone","tel",1],["title","Job title","text",1],["dept","Department"],["pos","Number of positions","number"],["exp","Experience required","select",0,EXP],["loc","Location"],["type","Employment type","select",0,YN],["mode","Work mode","select",0,["On-site","Hybrid","Remote"]],["time","Hiring timeline","select",0,["Immediate","Within 30 days","1–3 months"]],["desc","Job description / requirement","textarea",0]]},
resume:{btn:"Submit Resume",ok:"Resume submitted. We will reach out when a role matches your profile.",f:[["name","Full name","text",1],["email","Email","email",1],["phone","Phone","tel",1],["loc","Location"],["exp","Experience","select",0,EXP],["skills","Skills"],["role","Preferred role"],["ploc","Preferred location"],["cv","Resume upload","file",1]]},
apply:{btn:"Submit Application",ok:"Application submitted. Thank you for applying.",f:[["name","Full name","text",1],["email","Email","email",1],["phone","Phone","tel",1],["loc","Current location"],["exp","Total experience","select",0,EXP],["co","Current company"],["des","Current designation"],["role","Expected role"],["ploc","Preferred location"],["np","Notice period","select",0,["Immediate","15 days","30 days","60 days","90 days"]],["li","LinkedIn profile","url"],["cv","Resume upload","file",1],["cl","Cover letter","textarea",0]]},
contact:{btn:"Send Message",ok:"Message sent. We will get back to you soon.",f:[["name","Name","text",1],["email","Email","email",1],["phone","Phone","tel"],["company","Company"],["subject","Subject","text",1],["msg","Message","textarea",1]]}};
const fld=([n,l,t="text",r,o])=>{const id="f_"+n,q=r?" data-req":"";const el=t=="select"?`<select id="${id}" name="${n}"${q}><option value="">Select</option>${o.map(x=>`<option>${x}</option>`).join("")}</select>`:t=="textarea"?`<textarea id="${id}" name="${n}" rows="4"${q}></textarea>`:`<input id="${id}" name="${n}" type="${t}"${q}${t=="file"?' accept=".pdf,.doc,.docx"':""}>`;return `<div class="fld${t=="textarea"||t=="file"?" full":""}"><label for="${id}">${l}${r?" *":""}</label>${el}<div class="em" role="alert"></div></div>`};
const form=(k,extra="")=>{const c=FM[k];return `<form data-form data-ok="${c.ok}" novalidate class="card"><div class="fg">${c.f.map(fld).join("")}<div class="fld full"><label style="font-weight:400"><input type="checkbox" data-req style="width:auto;min-height:0;margin-right:8px">I agree to the <a href="#/terms" style="color:var(--blue)">terms</a> and <a href="#/privacy" style="color:var(--blue)">privacy policy</a>. *</label><div class="em" role="alert"></div></div>${extra}</div><button type="submit" class="btn b2" style="margin-top:8px">${c.btn}</button></form>`};
document.addEventListener("submit",e=>{const f=e.target.closest("form[data-form]");if(!f)return;e.preventDefault();let ok=true;
f.querySelectorAll("[data-req]").forEach(i=>{const p=i.closest(".fld"),v=i.value.trim();let m="";
if(i.type=="checkbox"){if(!i.checked)m="Accept the terms to continue."}else if(!v)m="This field is required.";
else if(i.type=="email"&&!/^\S+@\S+\.\S+$/.test(v))m="Enter a valid email, e.g. name@company.com.";
else if(i.type=="tel"&&!/^[+\d][\d\s-]{7,}$/.test(v))m="Enter a valid phone number.";
p.classList.toggle("err",!!m);p.querySelector(".em").textContent=m;if(m)ok=false});
if(!ok){f.querySelector(".err input,.err select,.err textarea")?.focus();return}
const b=f.querySelector("button[type=submit]");b.disabled=true;b.textContent="Submitting…";
/* TODO: replace with real API call, e.g. fetch('/api/...', {method:'POST', body:new FormData(f)}) */
setTimeout(()=>{f.outerHTML=`<div class="card ok"><i>✓</i><h3>Thank you!</h3><p>${f.dataset.ok}</p><a class="btn b2" href="#/">Back to home</a></div>`},900)});
