/* ============ COMPONENTS ============ */
const sh=(e,t,s="",c="")=>`<div class="sh ${c} rv"><div class="eb">${e}</div><h2>${t}</h2>${s?`<p>${s}</p>`:""}</div>`;
const ph=(h,ar="4/3")=>`<div class="ph" style="--h:${h};--ar:${ar}" role="img" aria-label="Placeholder image"></div>`;
const jc=j=>`<article class="card h jc rv"><div class="meta"><span class="pill">${j.type}</span><span class="pill">${j.mode}</span><span class="pill">Posted ${j.posted}</span></div><h3>${j.t}</h3><p style="margin:0">Confidential client · ${j.loc}</p><p style="margin:0">${j.exp} · ${j.ind}</p><div class="meta">${j.sk.map(s=>`<span class="pill" style="background:none;border:1px solid var(--line);color:var(--mut)">${s}</span>`).join("")}</div><div class="row" style="margin-top:8px"><a class="btn b2" href="#/jobs/${j.id}">View Details</a><a class="btn b3" href="#/apply/${j.id}">Apply Now</a></div></article>`;
const ctaBlock=()=>`<section class="sec"><div class="w"><div class="cta rv"><h2>Let's find the right talent. Together.</h2><p>Whether you're building a team or planning your next career move, ACE TALENT CONSULTING can help connect the right opportunity with the right talent.</p><div class="row"><a class="btn b1" href="#/employers">Hire Talent</a><a class="btn b3" href="#/jobs">Find a Job</a></div></div></div></section>`;
const faq=()=>`<section class="sec alt"><div class="w" style="max-width:820px">${sh("Questions, answered","Good partnerships start with clarity.")}${FAQ.map(q=>`<details class="rv"><summary>${q[0]}</summary><p>${q[1]}</p></details>`).join("")}</div></section>`;
const searchBar=()=>`<div class="sb"><div class="w"><form class="sf" id="jsf"><div><label for="q">Search jobs</label><input id="q" placeholder="Job title, keyword or skill"></div><div><label for="l">Location</label><input id="l" placeholder="City, state or location"></div><div><label for="x">Experience</label><select id="x"><option value="">Any experience</option>${EXP.map(x=>`<option>${x}</option>`).join("")}</select></div><div><label for="t">Job type</label><select id="t"><option value="">Any job type</option>${YN.map(x=>`<option>${x}</option>`).join("")}</select></div><button class="btn b2" type="submit">Search Jobs</button></form><p style="text-align:right;margin:12px 4px 0"><a href="#/jobs" style="color:var(--blue);font-weight:600">Browse all jobs →</a></p></div></div>`;
const page=(t,s,btns="")=>`<section class="ph2"><div class="w"><h1>${t}</h1><p>${s}</p><div class="row">${btns}</div></div></section>`;
const svcCard=s=>`<a class="card h rv" href="#/services/${s[0]}"><div class="ico">◆</div><h3>${s[1]}</h3><p>${s[2]}</p><b style="color:var(--blue)">${s[3]} →</b></a>`;
const indCard=(x,i)=>`<a class="card h rv" href="#/industries/${x[0]}" style="padding:0;overflow:hidden">${ph(200+i*22,"16/9")}<div style="padding:22px"><h3>${x[1]}</h3><p style="margin:0">${x[2]}</p></div></a>`;
/* ============ PAGES ============ */
const P={
home:()=>`<section class="hero"><div class="w hg"><div><h1>Connecting exceptional talent with exceptional opportunities.</h1><p>ACE TALENT CONSULTING helps organizations discover the right people and helps professionals find opportunities where they can grow, contribute and succeed.</p><div class="row"><a class="btn b1" href="#/employers">Hire Talent</a><a class="btn b3" href="#/jobs">Find Your Next Job</a></div><div class="tag">Talent consulting • Recruitment • Staffing</div></div><div class="hv">${ph(222,"4/4.4")}<div class="fl f1">Talent Matched<small>Screened profiles</small></div><div class="fl f2">Recruitment Solutions<small>Permanent & contract</small></div><div class="fl f3">Career Opportunities<small>Across industries</small></div></div></div></section>${searchBar()}
<section class="sec"><div class="w"><div class="st rv">${STATS.map(s=>`<div><b ${s[0]?`data-c="${s[0]}" data-s="${s[1]}"`:""}>${s[0]?"0":s[1]}</b><span>${s[2]}</span></div>`).join("")}</div></div></section>
<section class="sec alt"><div class="w"><div class="grid g2"><div class="card rv" style="padding:0;overflow:hidden">${ph(225,"16/8")}<div style="padding:28px"><h3>Looking for the right talent?</h3><p>Tell us what you need and our recruitment team will help you identify relevant professionals.</p><div class="row"><a class="btn b1" href="#/employers">Hire Talent</a><a class="btn b3" href="#/employers#req">Submit Requirement</a></div></div></div><div class="card rv" style="padding:0;overflow:hidden">${ph(160,"16/8")}<div style="padding:28px"><h3>Looking for your next opportunity?</h3><p>Explore opportunities aligned with your skills, experience and career goals.</p><div class="row"><a class="btn b2" href="#/jobs">Search Jobs</a><a class="btn b3" href="#/candidates">Submit Resume</a></div></div></div></div></div></section>
<section class="sec"><div class="w"><div class="grid g2" style="align-items:center"><div class="rv"><div class="eb">About ACE Talent Consulting</div><h2>Talent that moves businesses forward.</h2><p>ACE TALENT CONSULTING is a talent consulting, recruitment and staffing company focused on connecting businesses with capable professionals and helping candidates discover meaningful career opportunities.</p><ul class="ul">${["Recruitment expertise","Industry knowledge","Candidate network","Structured screening","Client-focused approach","Workforce solutions"].map(x=>`<li>${x}</li>`).join("")}</ul><a class="btn b2" href="#/about">Discover ACE Talent Consulting</a></div><div class="rv">${ph(215,"5/4")}</div></div></div></section>
<section class="sec alt"><div class="w">${sh("What we solve","Our talent solutions","From a single critical role to a workforce program, our services flex around what your business needs next.")}<div class="grid g3">${SV.map(svcCard).join("")}</div></div></section>
<section class="sec"><div class="w">${sh("How we work","From requirement to right hire.","A clear, considered process that keeps quality high and momentum moving.")}<div class="steps rv">${ST.map(s=>`<div class="step"><h3>${s[0]}</h3><p>${s[1]}</p></div>`).join("")}</div></div></section>
<section class="sec alt"><div class="w">${sh("Where we work","Recruitment expertise across industries","Sector understanding helps us ask better questions and recognize potential.")}<div class="grid g3">${IN.map(indCard).join("")}</div><p style="margin-top:28px"><a class="btn b2" href="#/industries">View All Industries</a></p></div></section>
<section class="sec"><div class="w">${sh("Why ACE","Why ACE Talent Consulting")}<div class="grid g3">${WHY.map(w=>`<div class="card h rv"><div class="ico">✓</div><h3>${w[0]}</h3><p style="margin:0">${w[1]}</p></div>`).join("")}</div></div></section>
<section class="sec alt"><div class="w"><div class="row" style="justify-content:space-between;align-items:end">${sh("Latest opportunities","A better next move may be closer than you think.","Placeholder roles. Edit the JB list to publish real ones.")}<a class="btn b3" href="#/jobs" style="margin-bottom:44px">View All Jobs</a></div><div class="grid g3">${JB.slice(0,3).map(jc).join("")}</div></div></section>
<section class="sec"><div class="w">${sh("Trusted by businesses","What clients say","Placeholder testimonials. Replace before launch.")}<div class="grid g3">${TS.map(t=>`<figure class="card rv" style="margin:0"><p>“${t[2]}”</p><b>${t[0]}</b><br><span style="color:var(--mut)">${t[1]}</span></figure>`).join("")}</div><div class="mq" style="margin-top:36px" aria-hidden="true"><div class="mt">${Array.from({length:16},(_,i)=>`<span>Client logo ${String(i%8+1).padStart(2,"0")}</span>`).join("")}</div></div></div></section>
<section class="sec alt"><div class="w"><div class="row" style="justify-content:space-between;align-items:end">${sh("From the field","Insights that help you hire better.")}<a class="btn b3" href="#/insights" style="margin-bottom:44px">Read all insights</a></div><div class="grid g3">${BL.map(b=>`<a class="rv" href="#/insights">${ph(b[3],"4/3")}<div class="eb" style="margin-top:16px">${b[0]}</div><h3>${b[1]}</h3><p>${b[2]}</p></a>`).join("")}</div></div></section>${faq()}${ctaBlock()}`,
about:()=>`${page("People. Potential. Possibilities.","ACE TALENT CONSULTING is a talent consulting, recruitment and staffing company connecting businesses with capable professionals.")}<section class="sec"><div class="w"><div class="grid g3">${[["Who we are","A recruitment and talent consulting partner built around people."],["What we do","Permanent hiring, contract staffing, executive search, TA, RPO and workforce solutions."],["Our approach","Understand the brief, know the person, then screen with care."],["Our mission","Connect the right people with the right opportunities."],["Our vision","To be the talent partner organizations and professionals trust."],["Our values","Clarity, care, integrity and follow-through."]].map(x=>`<div class="card h rv"><h3>${x[0]}</h3><p style="margin:0">${x[1]}</p></div>`).join("")}</div></div></section><section class="sec alt"><div class="w">${sh("Brand story","Our milestones","Editable placeholders.")}<div class="steps rv">${["Founded","First clients","Network growth","Pan India reach","Next chapter","Add milestone"].map(x=>`<div class="step"><h3>${x}</h3><p>Milestone description (placeholder).</p></div>`).join("")}</div></div></section>${ctaBlock()}`,
services:()=>`${page("Talent solutions designed around your business.","From a single critical role to a workforce program.")}<section class="sec"><div class="w"><div class="grid g3">${SV.map(svcCard).join("")}</div></div></section>${ctaBlock()}`,
service:id=>{const s=SV.find(x=>x[0]==id)||SV[0];return `${page(s[1],s[2],`<a class="btn b1" href="#/employers">Talk to Our Experts</a>`)}<section class="sec"><div class="w"><div class="grid g2"><div class="card"><h3>Key benefits</h3><ul class="ul"><li>Relevant, screened profiles</li><li>Faster turnaround</li><li>Dedicated recruiter support</li></ul></div><div class="card"><h3>Our process</h3><ul class="ul">${ST.map(x=>`<li><b>${x[0]}:</b> ${x[1]}</li>`).join("")}</ul></div></div></div></section>${ctaBlock()}`},
industries:()=>`${page("Recruitment expertise across industries","Sector understanding helps us ask better questions.")}<section class="sec"><div class="w"><div class="grid g3">${IN.map(indCard).join("")}</div></div></section>${ctaBlock()}`,
industry:id=>{const x=IN.find(i=>i[0]==id)||IN[0];return `${page(x[1],x[2],`<a class="btn b1" href="#/employers">Hire Talent</a>`)}<section class="sec"><div class="w"><div class="grid g3"><div class="card"><h3>Hiring requirements</h3><p>Placeholder: typical hiring needs in this sector.</p></div><div class="card"><h3>Roles we recruit for</h3><p>${x[2]}</p></div><div class="card"><h3>Our approach</h3><p>We learn the sector, screen for fit, and shortlist with context.</p></div></div></div></section>${ctaBlock()}`},
jobs:()=>{const opt=(k,a)=>`<option value="">All</option>${[...new Set(a)].map(v=>`<option${J[k]==v?" selected":""}>${v}</option>`).join("")}`;
const r=JB.filter(j=>(!J.q||(j.t+j.dept+j.sk.join()).toLowerCase().includes(J.q.toLowerCase()))&&(!J.loc||j.loc.toLowerCase().includes(J.loc.toLowerCase()))&&(!J.type||j.type==J.type)&&(!J.ind||j.ind==J.ind)&&(!J.mode||j.mode==J.mode)&&(!J.dept||j.dept==J.dept)&&(!J.exp||j.exp==J.exp)),n=Math.max(1,Math.ceil(r.length/4));J.page=Math.min(J.page||1,n);
return `${page("Find your next opportunity","Search curated opportunities from our network.")}<section class="sec"><div class="w jl"><form class="card fp" id="jf"><h3>Filters</h3><div><label>Keyword</label><input name="q" value="${J.q||""}" placeholder="Title or skill"></div><div><label>Location</label><input name="loc" value="${J.loc||""}" placeholder="City or state"></div><div><label>Experience</label><select name="exp">${opt("exp",JB.map(j=>j.exp))}</select></div><div><label>Industry</label><select name="ind">${opt("ind",JB.map(j=>j.ind))}</select></div><div><label>Job type</label><select name="type">${opt("type",JB.map(j=>j.type))}</select></div><div><label>Department</label><select name="dept">${opt("dept",JB.map(j=>j.dept))}</select></div><div><label>Work mode</label><select name="mode">${opt("mode",JB.map(j=>j.mode))}</select></div><button class="btn b2" type="submit">Search</button><button class="btn b3" type="reset" id="jr">Clear</button></form><div><p><b>${r.length}</b> jobs found</p><div class="grid">${r.slice((J.page-1)*4,J.page*4).map(jc).join("")||`<div class="card"><h3>No jobs match</h3><p>Try clearing a filter, or <a style="color:var(--blue)" href="#/candidates">submit your resume</a>.</p></div>`}</div><div class="pg">${Array.from({length:n},(_,i)=>`<button data-pg="${i+1}" class="${i+1==J.page?"on":""}" aria-label="Page ${i+1}">${i+1}</button>`).join("")}</div></div></div></section>`},
job:id=>{const j=JB.find(x=>x.id==id)||JB[0],u=encodeURIComponent(location.href);return `${page(j.t,`Confidential client · ${j.loc} · ${j.exp} · ${j.type} · ${j.mode} · Posted ${j.posted}`,`<a class="btn b1" href="#/apply/${j.id}">Apply Now</a>`)}<section class="sec"><div class="w" style="max-width:860px">${[["Job description","Placeholder description for this role. Replace with the real brief."],["Responsibilities","<ul class='ul'><li>Own day-to-day delivery for the function</li><li>Work with stakeholders</li><li>Report on outcomes</li></ul>"],["Required skills",`<ul class='ul'>${j.sk.map(s=>`<li>${s}</li>`).join("")}</ul>`],["Experience",j.exp],["Qualifications","Relevant degree or equivalent experience."],["Benefits","Competitive compensation and growth. Details shared during the process."]].map(x=>`<div class="card" style="margin-bottom:16px"><h3>${x[0]}</h3>${x[1].startsWith("<")?x[1]:`<p style="margin:0">${x[1]}</p>`}</div>`).join("")}<div class="row"><a class="btn b1" href="#/apply/${j.id}">Apply Now</a><a class="btn b3" target="_blank" rel="noopener" href="https://www.linkedin.com/sharing/share-offsite/?url=${u}">LinkedIn</a><a class="btn b3" target="_blank" rel="noopener" href="https://wa.me/?text=${u}">WhatsApp</a><a class="btn b3" href="mailto:?subject=${encodeURIComponent(j.t)}&body=${u}">Email</a></div></div></section>`},
apply:id=>{const j=JB.find(x=>x.id==id);return `${page("Apply for this job",j?j.t+" · "+j.loc:"Tell us about yourself.")}<section class="sec"><div class="w" style="max-width:860px">${form("apply")}</div></section>`},
employers:()=>`${page("Build your team with the right talent.","From individual positions to large-scale hiring requirements, ACE TALENT CONSULTING provides recruitment and staffing solutions designed around your business.",`<a class="btn b1" href="#/employers#req">Submit Requirement</a>`)}<section class="sec"><div class="w"><div class="grid g3">${["Permanent Hiring","Contract Staffing","Executive Search","High-Volume Hiring","Talent Acquisition","RPO","Workforce Solutions"].map(x=>`<div class="card h rv"><div class="ico">◆</div><h3 style="margin:0">${x}</h3></div>`).join("")}</div></div></section><section class="sec alt" id="req"><div class="w" style="max-width:860px">${sh("Hiring requirement","Tell us who you need")}${form("employer")}</div></section>`,
candidates:()=>`${page("Your career. Your next opportunity.","Search jobs, submit your resume and explore opportunities by industry and location.",`<a class="btn b1" href="#/jobs">Explore Jobs</a><a class="btn b3" href="#/candidates#cv">Submit Resume</a>`)}<section class="sec"><div class="w"><div class="grid g3">${["Search Jobs","Career Opportunities","Industry-wise Jobs","Location-wise Jobs","Career Resources"].map(x=>`<a class="card h rv" href="#/jobs"><h3 style="margin:0">${x}</h3></a>`).join("")}</div></div></section><section class="sec alt" id="cv"><div class="w" style="max-width:860px">${sh("Submit resume","Share your profile")}${form("resume")}</div></section>`,
contact:()=>`${page("Let's talk","Tell us about your hiring needs or your next career move.")}<section class="sec"><div class="w"><div class="grid g2"><div><h2>Get in touch</h2><p>ACE TALENT CONSULTING is here to help you hire better or find a better role.</p><p><b>Phone:</b> ${CO.phone}<br><b>Email:</b> ${CO.email}<br><b>Address:</b> ${CO.addr}</p><div class="ph" style="--h:220;--ar:16/9" role="img" aria-label="Map placeholder"></div></div>${form("contact")}</div></div></section>`,
insights:()=>`${page("Insights that help you hire better.","Placeholder articles.")}<section class="sec"><div class="w"><div class="grid g3">${BL.concat(BL).map(b=>`<div class="rv">${ph(b[3])}<div class="eb" style="margin-top:16px">${b[0]}</div><h3>${b[1]}</h3><p>${b[2]}</p></div>`).join("")}</div></div></section>`,
gallery:()=>`${page("Gallery","Team, events and workplace moments.")}<section class="sec"><div class="w"><div class="grid g3">${Array.from({length:9},(_,i)=>`<div class="rv">${ph(200+i*15,i%3==1?"3/4":"4/3")}</div>`).join("")}</div></div></section>`,
legal:t=>`${page(t,"Placeholder content. Replace with legally reviewed text.")}<section class="sec"><div class="w" style="max-width:820px"><p>Add your ${t.toLowerCase()} here.</p></div></section>`};
